### ISSUE TITLE
Automate the generation of the QC reports

### ISSUE THREAD

**Issue by edwardsnj** [cptac3-cdap/qc-reports#2]

**Comment by edwardsnj** [comment]
Blocked, waiting on #9

**Comment by edwardsnj** [comment]
Simina sent me this link: http://www.reed.edu/data-at-reed/software/R/markdown_multiple_reports.html look into this as a strategy...

**Comment by edwardsnj** [comment]
Install necessary R packages: 
install.packages("rmarkdown")
install.packages("markdown")
install.packages("knitr")

Download recent "pandoc": 

   https://github.com/jgm/pandoc/releases

Lots of other packages for R!

**Comment by edwardsnj** [comment]
The report itself needs dplyr ... and a bunch of other stuff. What a pain!

**Comment by tangshao2016** [comment]
For the visualization, a total of 10 depended packages are needed.

library(ggplot2)
library(reshape2)
library(dplyr)
library(knitr)
library(kableExtra)
library(RColorBrewer) ## generate palette
library(grid)
library(gridExtra)  ## to show the plots side by side
library(pander)      ## this package is used ot convert the .md file into
PDF
library(plotly)

I haven't had big problems installing them, but if you do have some, we
could discuss ways to address that.

**Comment by edwardsnj** [comment]
The reports have been integrated w/ the Galaxy CDAP infrastructure and are executed by script. Note that there are some strange issues in presentation which may be due to R version or package version or RStudio stuff. Dunno, but running things from the command-line and integration into the AWS-Galaxy instances has been done.
