### ISSUE TITLE
Fix errors in section titles in QC reports

### ISSUE THREAD

**Issue by edwardsnj** [cptac3-cdap/qc-reports#8]
From my script to patch the uploaded qc reports HTML files

    '1': 'Experimental Design Summary',
    '2': 'MS/MS Spectra',
    '2.1': 'Total MS/MS Spectra by Analytical Sample',
    '2.2': 'MS/MS Spectra for Fractions by Analytical Sample (box plot)',
    '2.3': 'MS/MS Spectra for Fractions by Analytical Sample (box plot, linked)',
    '2.4': 'MS/MS Spectra for Analytical Samples by Fraction',
    '2.5': 'MS/MS Spectra for Analytical Samples by Fraction (linked)',
    '2.6': 'MS/MS Spectra for Analytical Samples by Fraction (box plot)',
    '2.7': 'MS/MS Spectra for Analytical Samples by Fraction (box plot, linked)',
    '3': 'Precursor Intensity',
    '3.1': 'Precursor Intensity Percentiles for Analytical Samples by Fraction',
    '4': 'Precursor m/z',
    '4.1': 'Precursor m/z Percentiles for Analytical Samples by Fraction',
    '5': 'Precursor Molecular Weight',
    '5.1': 'Precursor Molecular Weight Percentiles for Analytical Samples by Fraction',
    '5.2': 'Precursor Molecular Weight Percentiles for Analytical Samples by Fraction',
    '6': 'MS/MS Spectra per Cycle',
    '6.1': 'MS/MS Spectra per Cycle for Analytical Samples by Fraction',
    '7': 'Precursor Charge State',
    '7.1': 'Overall Precursor Charge State Distribution',

Please pay attention to capitalization, etc.

**Comment by edwardsnj** [comment]
I have completed this task.

**Comment by tangshao2016** [comment]
Thanks. We haven't closed #7.


*Add text to each plot to explain how the values are extracted from the
files (and which metrics fields are involved) (#**7**)*

Clarification maybe needed for understanding ‘how the values are extracted
from the files’. In general, all the values we are getting from the QC
metric file are direct retrieval. For example, for analytical sample 1 and
fraction 1, we just access the value from the QC metric file (in matrix
format) using row and column index. All these values are precomputed so no
additional processing is needed.

In the following, I described the meaning of the metric and which field it
comes from based on sessions from 2 to 7.



2:

All values shown in session 2 are taken from the ‘numofMS2_ALL’ or
‘numofMS2_ID’ field from the metric file.

[1] 2.1: each point shows for a given analytical sample, the total MS/MS
spectra by summing up all fractions.

[2] 2.2 & 2.3: each point shows for each analytical sample’ fraction, the
number of MS/MS spectra. X axis indicates the analytical sample ID, while y
axis indicates the fraction ID.

[3] 2.4 & 2.5: identical to 2.2 & 2.3, each point shows the number of MS/MS
spectra for each analytical sample’ fraction. X axis indicates the fraction
ID, while y axis indicates the analytical sample ID.

[4] 2.6 & 2.7 are identical to 2.4 & 2.5.



3:

Each point shows a particular analytical sample’s (labeled in different
colors) specific fraction’s (plotted on x axis) precursor m/z under a
specific percentile scale. The value is taken from the
"minPrecursorMZ_ALL”, "PrecursorMZ5perc_ALL ", "PrecursorMZ25perc_ALL ",
"PrecursorMZ50perc_ALL ", "PrecursorMZ75perc_ALL ", "PrecursorMZ95perc_ALL
", and "maxPrecursorMZ_ALL" for mzML file and "minPrecursorMZ_ID”,
"PrecursorMZ5perc_ID ", "PrecursorMZ25perc_ID ", "PrecursorMZ50perc_ID ",
"PrecursorMZ75perc_ID ", "PrecursorMZ95perc_ID ", and "maxPrecursorMZ_ID"
for mzID file.



4:

Each point shows a particular analytical sample’s (labeled in different
colors) specific fraction’s (plotted on x axis) precursor intensity (by
log-10 scale) under a given percentile scale. The value is taken from the
"minPrecursorIntensity_ALL”, "PrecursorIntensity5perc_ALL ",
"PrecursorIntensity25perc_ALL ", "PrecursorIntensity50perc_ALL ",
"PrecursorIntensity75perc_ALL ", "PrecursorIntensity95perc_ALL ", and
"maxPrecursorIntensity_ALL" for mzML file and "minPrecursorIntensity_ID”,
"PrecursorIntensity5perc_ID ", "PrecursorIntensity25perc_ID ",
"PrecursorIntensity50perc_ID ", "PrecursorIntensity75perc_ID ",
"PrecursorIntensity95perc_ID ",  and "maxPrecursorIntensity_ID" for mzID
file.

5:

Each point shows a particular analytical sample’s (labeled in different
colors) specific fraction’s (plotted on x axis) precursor weight under a
given percentile scale. The value is taken from the "minPrecursorMW_ALL”,
"PrecursorMW5perc_ALL ", "PrecursorMW25perc_ALL ", "PrecursorMW50perc_ALL
", "PrecursorMW75perc_ALL ", "PrecursorMW95perc_ALL ", and
"maxPrecursorMW_ALL" for mzML file and "minPrecursorMW_ID”,
"PrecursorMW5perc_ID ", "PrecursorMW25perc_ID ", "PrecursorMW50perc_ID ",
"PrecursorMW75perc_ID ", "PrecursorMW95perc_ID ", and "maxPrecursorMW_ID"
for mzID file.



6

Each point shows a particular analytical sample’s (labeled in different
colors) specific fraction’s (plotted on x axis) number of MS/MS per Cycle
under a given percentile scale. The value is taken from the
"minMS2perMS1_ALL”, "MS2perMS15perc_ALL ", "MS2perMS125perc_ALL ",
"MS2perMS150perc_ALL ", "MS2perMS175perc_ALL ", "MS2perMS195perc_ALL ", and
"maxMS2perMS1_ALL" for mzML file and "minMS2perMS1_ID”, "MS2perMS15perc_ID
", "MS2perMS125perc_ID ", "MS2perMS150perc_ID ", "MS2perMS175perc_ID ",
"MS2perMS195perc_ID ", and "maxMS2perMS1_ID" for mzID file.



7:

Each bar shows the proportions of MS/MS spectra for a given MS/MS charge
state. Each value is computed from counting the field ‘numofMS2_ID’ based
on charge states. The computed values are available at column "MS2Charge1",
"MS2Charge2", "MS2Charge3", "MS2Charge4", and "MS2Charge5andHigher".
